# Generated by Django 4.2.7 on 2023-11-19 20:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Blusa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(help_text='Ingrese el nombre del articulo.', max_length=50, unique=True)),
                ('descripcion', models.CharField(help_text='Agregue una descripcion al articulo', max_length=100)),
                ('talla', models.CharField(blank=True, choices=[('XS', 'Extra Small'), ('S', 'Small'), ('M', 'Medium'), ('L', 'Large'), ('XL', 'Extra Large')], default='XS', help_text='Talla del producto', max_length=2)),
            ],
            options={
                'ordering': ['nombre', 'talla', 'marca'],
            },
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, null=True)),
                ('email', models.CharField(max_length=200)),
                ('phone', models.CharField(help_text='Ingrese su numero en formato de 8 digitos.', max_length=8)),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Estilo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('style', models.CharField(help_text='Añada un estilo (formal, casual, manga corta, etc).', max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Marca',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand', models.CharField(help_text='Registre una marca.', max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_ordered', models.DateTimeField(auto_now_add=True)),
                ('complete', models.BooleanField(default=False, null=True)),
                ('transaction_id', models.CharField(max_length=100, null=True)),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='store.customer')),
            ],
        ),
        migrations.CreateModel(
            name='Pantalon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(help_text='Ingrese el nombre del articulo.', max_length=50, unique=True)),
                ('descripcion', models.CharField(help_text='Agregue una descripcion al articulo.', max_length=100)),
                ('talla', models.CharField(blank=True, choices=[('0', 'Talla 0'), ('1', 'Talla 1'), ('3', 'Talla 3'), ('5', 'Talla 5'), ('9', 'Talla 9')], default='XS', help_text='Talla del producto', max_length=1)),
                ('estilo', models.ManyToManyField(help_text='Seleccione el o los estilos de este articulo.', to='store.estilo')),
                ('marca', models.ForeignKey(help_text='Seleccione la marca de este articulo.', null=True, on_delete=django.db.models.deletion.SET_NULL, to='store.marca')),
            ],
            options={
                'ordering': ['nombre', 'talla', 'marca'],
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, null=True)),
                ('price', models.FloatField()),
                ('digital', models.BooleanField(blank=True, default=False, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Vestido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(help_text='Ingrese el nombre del articulo.', max_length=50, unique=True)),
                ('descripcion', models.CharField(help_text='Agregue una descripcion al articulo.', max_length=100)),
                ('talla', models.CharField(blank=True, choices=[('XS', 'Extra Small'), ('S', 'Small'), ('M', 'Medium'), ('L', 'Large'), ('XL', 'Extra Large')], default='XS', help_text='Talla del producto', max_length=2)),
                ('estilo', models.ManyToManyField(help_text='Seleccione el o los estilos de este articulo.', to='store.estilo')),
                ('marca', models.ForeignKey(help_text='Seleccione la marca de este articulo.', null=True, on_delete=django.db.models.deletion.SET_NULL, to='store.marca')),
            ],
            options={
                'ordering': ['nombre', 'talla', 'marca'],
            },
        ),
        migrations.CreateModel(
            name='VestidoInstance',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, help_text='ID unico del articulo.', primary_key=True, serialize=False, unique=True)),
                ('status', models.CharField(blank=True, choices=[('a', 'Disponible'), ('w', 'En solicitud'), ('d', 'Declinado'), ('c', 'Comprado')], default='a', help_text='Talla del producto', max_length=1)),
                ('blusa', models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, to='store.vestido')),
                ('comprador', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ShippingAddress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=200)),
                ('distrito', models.CharField(max_length=200)),
                ('canton', models.CharField(max_length=200)),
                ('provincia', models.CharField(max_length=200)),
                ('zipcode', models.CharField(max_length=200)),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('customer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='store.customer')),
                ('order', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='store.order')),
            ],
        ),
        migrations.CreateModel(
            name='PantalonInstance',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, help_text='ID unico del articulo.', primary_key=True, serialize=False, unique=True)),
                ('status', models.CharField(blank=True, choices=[('a', 'Disponible'), ('w', 'En solicitud'), ('d', 'Declinado'), ('c', 'Comprado')], default='a', help_text='Talla del producto', max_length=1)),
                ('comprador', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('pantalon', models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, to='store.pantalon')),
            ],
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(blank=True, default=0, null=True)),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('order', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='store.order')),
                ('product', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='store.product')),
            ],
        ),
        migrations.CreateModel(
            name='BlusaInstance',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, help_text='ID unico del articulo.', primary_key=True, serialize=False, unique=True)),
                ('status', models.CharField(blank=True, choices=[('a', 'Disponible'), ('w', 'En solicitud'), ('d', 'Declinado'), ('c', 'Comprado')], default='a', help_text='Talla del producto', max_length=1)),
                ('blusa', models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, to='store.blusa')),
                ('comprador', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='blusa',
            name='estilo',
            field=models.ManyToManyField(help_text='Seleccione el o los estilos de este articulo.', to='store.estilo'),
        ),
        migrations.AddField(
            model_name='blusa',
            name='marca',
            field=models.ForeignKey(help_text='Seleccione la marca de este articulo.', null=True, on_delete=django.db.models.deletion.SET_NULL, to='store.marca'),
        ),
    ]
