# Generated by Django 4.2.7 on 2023-11-20 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_alter_shippingaddress_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estilo',
            name='style',
            field=models.CharField(help_text='Añada un estilo (formal, casual, manga corta, etc).', max_length=50, unique=True, verbose_name='Estilo'),
        ),
    ]
