# Generated by Django 4.2.7 on 2023-11-20 15:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_alter_estilo_style'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='vestido',
            options={'ordering': ['nombre', 'talla']},
        ),
    ]
