# Generated by Django 4.2.7 on 2023-11-20 15:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0006_alter_vestido_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='vestido',
            options={'ordering': ['nombre', 'talla', 'marca']},
        ),
    ]
