# Generated by Django 4.2.7 on 2023-11-21 15:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0007_alter_vestido_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blusainstance',
            name='blusa',
        ),
        migrations.RemoveField(
            model_name='blusainstance',
            name='comprador',
        ),
        migrations.RemoveField(
            model_name='pantalon',
            name='estilo',
        ),
        migrations.RemoveField(
            model_name='pantalon',
            name='marca',
        ),
        migrations.RemoveField(
            model_name='pantaloninstance',
            name='comprador',
        ),
        migrations.RemoveField(
            model_name='pantaloninstance',
            name='pantalon',
        ),
        migrations.RemoveField(
            model_name='vestido',
            name='estilo',
        ),
        migrations.RemoveField(
            model_name='vestido',
            name='marca',
        ),
        migrations.RemoveField(
            model_name='vestidoinstance',
            name='comprador',
        ),
        migrations.RemoveField(
            model_name='vestidoinstance',
            name='vestido',
        ),
        migrations.AddField(
            model_name='order',
            name='status',
            field=models.CharField(blank=True, choices=[('a', 'Disponible'), ('w', 'En solicitud'), ('d', 'Declinado'), ('c', 'Comprado')], default='a', help_text='Talla del producto', max_length=1),
        ),
        migrations.AddField(
            model_name='product',
            name='description',
            field=models.CharField(help_text='Agregue una descripcion al articulo.', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='estilo',
            field=models.ForeignKey(help_text='Seleccione el o los estilos de este articulo.', null=True, on_delete=django.db.models.deletion.SET_NULL, to='store.estilo'),
        ),
        migrations.AddField(
            model_name='product',
            name='marca',
            field=models.ForeignKey(help_text='Seleccione la marca de este articulo.', null=True, on_delete=django.db.models.deletion.SET_NULL, to='store.marca'),
        ),
        migrations.AlterField(
            model_name='estilo',
            name='style',
            field=models.CharField(help_text='Añada un estilo (Blusa, vestido, pantalon...)', max_length=50, unique=True),
        ),
        migrations.DeleteModel(
            name='Blusa',
        ),
        migrations.DeleteModel(
            name='BlusaInstance',
        ),
        migrations.DeleteModel(
            name='Pantalon',
        ),
        migrations.DeleteModel(
            name='PantalonInstance',
        ),
        migrations.DeleteModel(
            name='Vestido',
        ),
        migrations.DeleteModel(
            name='VestidoInstance',
        ),
    ]
