# Generated by Django 4.2.7 on 2023-11-21 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0009_product_talla'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='talla',
            field=models.CharField(blank=True, help_text='Agregue la talla de la prenda.', max_length=10, null=True),
        ),
    ]
