# Generated by Django 4.2.7 on 2023-11-24 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0011_alter_order_complete'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='status',
        ),
        migrations.AddField(
            model_name='orderitem',
            name='status',
            field=models.CharField(blank=True, choices=[('w', 'En solicitud'), ('d', 'Declinado'), ('c', 'Comprado')], default='w', help_text='Estado del producto', max_length=1),
        ),
    ]
